#+title: An enhanced inline patch for GNU Emacs

[[https://github.com/takaxp/ns-inline-patch/actions?query=workflow%3A%22Build+NS+with+inline-patch+%28HEAD%29%22][https://github.com/takaxp/ns-inline-patch/workflows/Build%20NS%20with%20inline-patch%20(HEAD)/badge.svg]]
[[https://github.com/takaxp/ns-inline-patch/actions?query=workflow%3A%22Build+NS+with+inline-patch+%2827.0%29%22][https://github.com/takaxp/ns-inline-patch/workflows/Build%20NS%20with%20inline-patch%20(27.0)/badge.svg]]
[[https://github.com/takaxp/ns-inline-patch/actions?query=workflow%3A%22Build+NS+with+inline-patch+%2826.3%29%22][https://github.com/takaxp/ns-inline-patch/workflows/Build%20NS%20with%20inline-patch%20(26.3)/badge.svg]]

see https://qiita.com/takaxp/items/e07bb286d80fa9dd8e05 and https://qiita.com/takaxp/items/6a7f9b26eb1b1a8237a0

Note: Version 27.2 has been released. The inline patch (emacs-27.1-inline.patch) can be still utilized to 27.2. Installer packages for Intel-based Mac and Apple Silicon M1 Mac will also be available soon from this repository (possibly end of march).

** Supported features

 - avoid "M-x あ"
 - faces for composing text
 - non ja locale
 - directly change input source

** Supported Emacs version

 - Emacs HEAD (emacs-head-inline.patch)
 - Emacs 27.1 (emacs-27.1-inline.patch)
 - Emacs 26.3, 26.2, 26.1 (emacs-25.2-inline.patch)
 - Emacs 25.3, 25.2 (emacs-25.2-inline.patch)

** Integrated functions

 - M-x mac-build-info

** How to use?

Add the following code to your init.el.

#+begin_src emacs-lisp
(when (and (memq window-system '(ns nil))
           (fboundp 'mac-get-current-input-source))
  (when (version< "27.0" emacs-version)
    ;; Required for some cases when auto detection is failed or the locale is "en".
    (custom-set-variables
     '(mac-default-input-source "com.google.inputmethod.Japanese.base")))
  (mac-input-method-mode 1))
#+end_src

** Build scripts

For your convenience, some build scripts are provided. Before you run the script, please run =setup.sh= first.

#+begin_src sh
sh ./build/setup.sh
sh ./build/emacs-27.1.sh
#+end_src

If your environment for building Emacs is under PROXY, you can use =emacs-mirror= to get Emacs source codes. Please change the URL of the git repository specified in =emacs-head.sh= and =emacs-27.1.sh= if needed.

** Pre-built distribution package

You can download my pre-built Emacs 26.3 and 27.1 with ns-inline patch. =Emacs.app= will be installed under =/Applications/Emacs-takaxp= in your macOS. The pkg contains =GnuTLS= and it supports Catalina only.

 - https://pxaka.tokyo/emacs/pkg/emacs-27.1.pkg (51.3MB, MD5:0c7048d147dea6fcdda638a25b161af8)
 - https://pxaka.tokyo/emacs/pkg/emacs-26.3.pkg (52.9MB, MD5:1868c787177f515f18f500ce6b898b05)

Additionally, the following package is "WITHOUT" inline-patch NS build. In this case, =Emacs.app= will be installed under =/Applications/Emacs-takaxp/pure=.
 - [[https://pxaka.tokyo/emacs/pkg/emacs-27.1_pure.pkg]] (51.3MB, MD5:fdd14baf87ed4f903b5b02c4e1dd022c)

Integrated dynamic libraries:

 - libffi.7.dylib
 - libgmp.10.dylib
 - libgnutls.30.dylib
 - libhogweed.6.dylib
 - libidn2.0.dylib
 - libintl.8.dylib
 - libnettle.8.dylib
 - libp11-kit.0.dylib
 - libtasn1.6.dylib
 - libunistring.2.dylib

The =system-configuration-features= is:

=NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS PDUMPER=

Enjoy!

