name: Clean up keychain and provisioning profile
description: 'Cleanup keychain DB and other information'
runs:
  using: "composite"
  steps:
    - run: |
        security delete-keychain $RUNNER_TEMP/app-signing.keychain-db
        rm ~/Library/MobileDevice/Provisioning\ Profiles/build_pp.provisionprofile
        rm $RUNNER_TEMP/orz_id
      shell: bash
