name: Export generated files
description: 'Export pkg and md5 file to an external server'
runs:
  using: "composite"
  steps:
    - run: |
        ID_PATH=$RUNNER_TEMP/orz_id
        rm -f ~/.ssh/known_hosts
        echo -n "$ORZ_ID_BASE64" | base64 --decode -o $ID_PATH
        chmod 600 $ID_PATH
        sftp -b release/upload.bat -o StrictHostKeyChecking=no -i $ID_PATH -P $ORZ_PORT github-ci@$ORZ_HOST
      shell: bash
